### ISSUE TITLE
Text in the HELM box is not wrapped

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#100]
If I copy text from an email with extremely long lines of text into the HELM text box, it is displayed with the text going beyond the text box limits. 

![image](https://cloud.githubusercontent.com/assets/3986896/25124450/abe9dece-2423-11e7-8317-c7871eef4be8.png)

It should be wrapped to stay within the box.

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
Confirmed fixed.
