### ISSUE TITLE
Structure monomers not connected 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#103]
![image](https://cloud.githubusercontent.com/assets/3986896/25391737/cecf215a-29ce-11e7-9974-abe11f03c667.png)

**Comment by scilligence** [comment]
Fixed in 2017-04-29 update

**Comment by ClairePA** [comment]
Can't check as antisense strand can't be generated.

**Comment by scilligence** [comment]
Sorry, this was caused in my last change.  It is fixed now.

**Comment by ClairePA** [comment]
Confirmed fixed.
