### ISSUE TITLE
RNA base ID is wrong for complementary strand

### ISSUE THREAD

**Issue by scilligence** [PistoiaHELM/HELMWebEditor#104]

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
Can't check as clicking on 'Create complementary strand' does nothing now.
![image](https://cloud.githubusercontent.com/assets/3986896/25660397/f220b372-3003-11e7-81b0-ef341a8974e4.png)

**Comment by scilligence** [comment]
Sorry, this was caused in my last change.  It is fixed now.

**Comment by ClairePA** [comment]
The numbering seems to be correct, but the find/replace function does not work for position. Will log as a separate issue. Close this one.
