### ISSUE TITLE
Find/replace does not work with position number

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#107]
If I use the position number to identify which monomer should be replaced I get no results. 

![image](https://cloud.githubusercontent.com/assets/3986896/25800155/06876c5e-33e0-11e7-89b7-ce684c0c0824.png)

![image](https://cloud.githubusercontent.com/assets/3986896/25800168/13b7d436-33e0-11e7-95e8-49a4f395187b.png)

**Comment by scilligence** [comment]
fixed 2017-05-09 update

**Comment by ClairePA** [comment]
Confirmed fixed.
