### ISSUE TITLE
Load HELM sequence fails 

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#109]
[2017-05-21_15-36-44.mp4.zip](https://github.com/PistoiaHELM/HELMWebEditor/files/1017290/2017-05-21_15-36-44.mp4.zip)

When entering a HELM sequence in the sequence field and clicking Apply, the attached error is showing up.

![2017-05-20_15-36-28](https://cloud.githubusercontent.com/assets/8645925/26278890/0afb82ba-3d73-11e7-85d4-7bc7cb01d262.png)

To reproduce:
- Enter a natural sequence. For ex: ATCG
   and click Apply. The Canvas is correctly populated
- Go to HELM tab of sequence, and change "RNA1{r(A)p.r(T)p.r(C)p.r(G)}$$$$V2.0" to "RNA1{r(G)p.r(T)p.r(C)p.r(G)}$$$$V2.0" or anything else.

You will see the error message.

**Comment by ypotier** [comment]
I added a video (in a zip file) in the bug report

**Comment by scilligence** [comment]
Fixed 2017-05-21 update

**Comment by ypotier** [comment]
Tested and issue resolved.
