### ISSUE TITLE
Unknown monomers are stripped without warning

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#110]
Steps:

Type a 

- HELM string into the HELM box which contains monomers not present in the current monomer list
- Click 'apply'
- The HELM string is modified to remove the unknown monomers and the structure displayed simply misses them out. 

The user should be warned that there are unknown monomers and informed about the action that will be taken.

**Comment by scilligence** [comment]
Could you give one example HELM string?

**Comment by ClairePA** [comment]
RNA1{[moe](G)[sp].[moe]([m5C])[sp].[moe]([m5C])[sp].[moe](T)[sp].[moe]([m5C])[sp].[dr](A)[sp].[dr](G)[sp].[dr](T)[sp].[dr]([m5C])[sp].[dr](T)[sp].[dr](G)[sp].[dr]([m5C])[sp].[dr](T)[sp].[dr](T)[sp].[dr]([m5C])[sp].[moe](G)[sp].[moe]([m5C])[sp].[moe](A)[sp].[moe]([m5C])[sp].[moe]([m5C])[sp]}$$$$

**Comment by scilligence** [comment]
fixed 2017-05-21s

**Comment by ClairePA** [comment]
Now it displays an error message stating that there is an unknown monomer "o". There was no monomer "o" in the HELM string, so this is incorrect. 

Also, the functionality to strip the monomer was useful behaviour, as you still got the rest of the molecule imported. Please reinstate this and make the error message state exactly which monomers have been removed, preferably in a single box so the user does not have to click through multiple error boxes. 

![image](https://cloud.githubusercontent.com/assets/3986896/26363372/ba0bd644-3fd8-11e7-9e49-318f7f50a52d.png)

**Comment by ClairePA** [comment]
Confirmed fixed.
