### ISSUE TITLE
zoom causes unintended centering of molecule

### ISSUE THREAD

**Issue by milton900807** [PistoiaHELM/HELMWebEditor#112]
When you move the structure.. and then zoom the structure is auto-centered.  This is a bit of a pain for example : many time you want to zoom into a five prime conjugate of a long oligo... 

if you move to the five prime and then click zoom the five prime disappears.

**Comment by scilligence** [comment]
If you explore the structure, the Move tool is the best one: (1) dragging to move; (2) rolling the wheel to zoom:
![image](https://user-images.githubusercontent.com/19560173/27193095-acab1406-51cb-11e7-926c-eae342a5ed84.png)

**Comment by ClairePA** [comment]
Can't the zoom buttons work like the mouse wheel? I think that would solve the problem.

**Comment by ClairePA** [comment]
Zooming using the menu option still doesn't act like the mouse wheel.

**Comment by scilligence** [comment]
Fixed 2017-08-31 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
