### ISSUE TITLE
Draw Bond tool/button

### ISSUE THREAD

**Issue by milton900807** [PistoiaHELM/HELMWebEditor#113]
It needs to be clear that after you select something... and you want to connect two monomers you should be able to click a button and then draw a bond between them.  At the moment it is not clear and this causes users to do unintended dropping of additional monomers onto the canvas when they intended to draw a bond.

**Comment by scilligence** [comment]
Fixed 2017-08-31 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
