### ISSUE TITLE
Definitions of R-groups for monomers

### ISSUE THREAD

**Issue by MarkusWeisser** [PistoiaHELM/HELMWebEditor#114]
Currently, R groups are difined within JSDraw by highlighting a residue (green circle) and type in the R group name (R1, R2, ....). Unexperienced users are not aware of this procedere.
Since this is a major function of the monomer registration dialog, I would recommend to have a button for the R-group definition on this dialog. Clicking on the button woll show a select-list with the possible R-groups.

**Comment by scilligence** [comment]
Could you give a screenshot, so we know where to set up this list?  Thanks.

**Comment by MarkusWeisser** [comment]
![image](https://user-images.githubusercontent.com/6429669/34246264-1ae228b4-e62e-11e7-8525-3fdf26436f65.png)

Should be similar to Java HELM editor.

**Comment by scilligence** [comment]
Fixed in 2018-01-01 update

**Comment by ClairePA** [comment]
The new UI looks better, but R should not be part of the list. R1, R2, R3, R4 and R5 are fine.

**Comment by scilligence** [comment]
fixed in 2018-01-10 update

**Comment by ClairePA** [comment]
Confirmed fixed.
