### ISSUE TITLE
Draw bond stop working after toolbar functionality is used

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#117]
If I load a polymer on the canvas, I can add new monomers and add bonds.
If I decide to use the eraser functionality for example and delete a monomer, then add a new one to the canvas, I cannot seem to be able to draw the bonds again. Since there is no draw bon button I cannot get the functionality again (https://github.com/PistoiaHELM/HELMWebEditor/issues/113).

See attached video for demo
[2017-07-21_11-58-44.mp4.zip](https://github.com/PistoiaHELM/HELMWebEditor/files/1166057/2017-07-21_11-58-44.mp4.zip)

**Comment by scilligence** [comment]
Fixed 2017-08-31 update

**Comment by ypotier** [comment]
Tested and fixed approved.
