### ISSUE TITLE
Only one of the four ambiguous monomers is implemented. 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#118]
It is possible to define a * monomer, but not X, N or _. See the extract below from the HELM specification. 

5.1.8. Monomer Ambiguity
Unknown monomers can represented by four different characters:
•   * The character “*” represents 0..n unknown monomers.
•   X The character “X” represents one single unknown amino acid in a PEPTIDE polymer.
•   N The character “N” represents one single unknown base in a RNA polymer.
•   _ The character “_” represents a deleted or missing single monomer. This is typically used for list elements (see  section List Elements)

**Comment by scilligence** [comment]
fixed in 2017-09-12 update

**Comment by ClairePA** [comment]
I can't work out how to add X, N or _. 

I can add * using the 'monomer attributes' box, but don't know how to add the others. 

This method of adding ambiguous monomers is not clear even for *. We need to have a discussion about how the UI works for this example.

**Comment by scilligence** [comment]
Fixed in 2017-12-1 update

**Comment by ClairePA** [comment]
I can see *, _ and X as peptide monomers, but nothing under nucleotide or chem.

**Comment by scilligence** [comment]
Not quite sure what should be used for the ambiguity of nucleotide and chem.

**Comment by ClairePA** [comment]
Nucleotides should have *, _ and N
Chem should have *.

**Comment by scilligence** [comment]
Are there some example HELM notations?  So we know how to generate the HELM string.

**Comment by ClairePA** [comment]
RNA1{R(*)P.R(C)P.*(N)P.R(G)P}$$$$V2.0 

CHEM1{*}|CHEM2{[sDBL]}|CHEM3{[SMPEG2]}$CHEM2,CHEM3,1:R2-1:R1|CHEM1,CHEM2,1:R1-1:R1$$$V2.0

**Comment by scilligence** [comment]
2017-12-09 update: * is added to CHEM

**Comment by scilligence** [comment]
Confirmed in today's meeting:
-------------------------
Base: _, N, *
Ribose: *
P: *
Combo: *

**Comment by scilligence** [comment]
Fixed in 2017-12-13 update

**Comment by ClairePA** [comment]
Confirmed fixed.
