### ISSUE TITLE
You should not be able to enter a % in the ratio box

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#121]
Ratios for groups must be specified using numbers only. the % character or other non-numeric characters should not be permitted.

**Comment by ClairePA** [comment]
Validation is now implemented for ambiguous bonds.

It still needs to be added for unconnected groups.

**Comment by scilligence** [comment]
Fixed in 2017-11-13

**Comment by ClairePA** [comment]
It now checks whether the entry is a number, but does not prevent something else being entered. 

![image](https://user-images.githubusercontent.com/3986896/32730918-5d39f672-c880-11e7-8995-51969884c56c.png)

![image](https://user-images.githubusercontent.com/3986896/32730951-6bc7ef6e-c880-11e7-9332-8551b7b2bcdb.png)

**Comment by scilligence** [comment]
I am not sure how "g" is entered here.  Could you write down the steps to reproduce?

**Comment by ClairePA** [comment]
1. create peptide.
2. create group.
3. right click on group and select set attributes.
4. type g into ratio box and click save.
5. OK the error message stating that a number is required.
6. The g is displayed on the group as shown in the picture above. 

The validation is being done as the error is displayed, however the incorrect entry should not be accepted and displayed.

**Comment by scilligence** [comment]
It looks like this happens only in Edge

**Comment by scilligence** [comment]
Fixed in 2017-12-1 update

**Comment by ClairePA** [comment]
Confirmed fixed. Thanks.
