### ISSUE TITLE
Blob types need to be defined

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#122]
The current implementation includes 3 blob types: antibody, gold particle and protein. 

![image](https://user-images.githubusercontent.com/3986896/31171757-caeab7ee-a8f8-11e7-93a2-60a959800c3b.png)

Antibody and protein should be removed as these can be represented in other ways. 

The list should include 'gold particle' and 'bead' and allow the user to add their own annotation.

**Comment by scilligence** [comment]
fixed in 2017-10-10 update.  Custom types can be defined as below:
org.helm.webeditor.blobtypes = ["Bead", "Gold Particle", "Other"];

I recommend to have Antibody and Protein there.  For an ADC, if the Antibody is unknown, users can use this way to express it.

**Comment by ClairePA** [comment]
If there is an unknown peptide, you should represent that as a * monomer of type peptide. The blob is for more generally unknown entities. We should add that recommendation to the user guide.

**Comment by ClairePA** [comment]
Discussed the blob types with the HELM team and confirmed that Gold particle and Bead are sufficient for now. Peptide and antibody should not be used.
