### ISSUE TITLE
Can't change the number on brackets on the canvas

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#126]
I can add brackets to a polymer and have a drop down box to add the number of recurrences as below:

![image](https://user-images.githubusercontent.com/3986896/31334331-cc4a29a8-ace5-11e7-94ae-2f4f1b7763fb.png)

The drop down does not contain anything. You add a number by typing, so either change to a text box or make it a true drop-down list. 

Once a number has been added, it is not possible to change it.

**Comment by scilligence** [comment]
To change it, mouse-hover the number then press keyboard ENTER key.

**Comment by ClairePA** [comment]
OK, that works, but no one is going to remember how to do it. It should be possible to edit the numbers by clicking or double-clicking the brackets or number.

**Comment by scilligence** [comment]
Fixed in 2018-01-01 update: Use Right-click context menu

**Comment by ClairePA** [comment]
To be honest I think this is worse. You have to right-click the middle of the bracket whereas the intuitive place to click is the number itself. Also, it is not obvious what "set subscript" means. You should be able to click on the number and change it to something else without the need for a description at all.

**Comment by scilligence** [comment]
Could you suggest a solution?  Sometime it has a number there, and sometime it might not have subscript at all.

**Comment by ClairePA** [comment]
I would like the following:

I draw a set of brackets and see this:

![image](https://user-images.githubusercontent.com/3986896/34558212-ff2f693a-f134-11e7-8f8b-ab07ed1d6a15.png)

This is good, but the drop down list should contain numbers (up to 100) and should default to 1. It should not be possible to have nothing selected since there is no point to the brackets if there is no repeat. 

Once I have selected a number a clicked away from them I see this:
![image](https://user-images.githubusercontent.com/3986896/34558342-a4231cb6-f135-11e7-816a-2c57bc14c311.png)

This is also fine. 
I can highlight either the centre of the bracket by hovering near the middle of one bracket.

![image](https://user-images.githubusercontent.com/3986896/34558403-ea55f352-f135-11e7-9948-e4ae21e860c0.png)

or the number at the bottom of the bracket by hovering there;

![image](https://user-images.githubusercontent.com/3986896/34558426-037980d8-f136-11e7-846b-ee310b5862c6.png)

I would like to be able to click on the number and the drop down menu reappear as it did when I originally drew the bracket. 

![image](https://user-images.githubusercontent.com/3986896/34558467-2cd2e50a-f136-11e7-82b6-488891b207ca.png)

I can then select whichever new number I want from the list.

**Comment by scilligence** [comment]
Fixed in 2018-01-08 update. Now it is able to enter text edit mode by clicking on the number when it is bracket tool.

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
