### ISSUE TITLE
Moving brackets does not change the HELM string

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#127]
I can create a HELM structure with a repeating unit.

![image](https://user-images.githubusercontent.com/3986896/31334896-20e294c6-ace8-11e7-907c-35d0fcc0112c.png)

If I change the location of the bracket, the HELM string does not change. 

![image](https://user-images.githubusercontent.com/3986896/31334924-3fa7e082-ace8-11e7-9fbc-236b27b5502d.png)

**Comment by scilligence** [comment]
Fixed in 2017-10-17 update

**Comment by ClairePA** [comment]
Still looks the same to me... I can't see the fix.

**Comment by scilligence** [comment]
Fixed in 2017-10-24 update

**Comment by ClairePA** [comment]
Looks perfect, Thanks!
