### ISSUE TITLE
Brackets do not affect the molecule properties or structure view

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#128]
If I enter a structure and add brackets to indicate a repeating unit, the repeated unit information is not included in the structure display.

![image](https://user-images.githubusercontent.com/3986896/31337647-313e65be-acf4-11e7-9780-5f7a1d26c7b6.png)

Or the structure properties - 

![image](https://user-images.githubusercontent.com/3986896/31337666-48f81ae2-acf4-11e7-834b-ed6e747adf37.png)

**Comment by scilligence** [comment]
This means there are 4 terminal in this end, but there is one R1 availble to connect.

**Comment by ClairePA** [comment]
??? I don't understand the comment.

**Comment by scilligence** [comment]
In this picture above, it indicates there are 4 R(A)P- connecting to -R(C)P-.  But -R(C)P- have only one R1 to be connected.

**Comment by ClairePA** [comment]
The picture above should not represent  4 R(A)P- connecting to -R(C)P- 
That particular set of brackets should mean R(A)P.R(A)P.R(A)P.R(A)P.R(C)P.R(C)P
Your interpretation of the HELM rules is incorrect.

**Comment by scilligence** [comment]
fixed in 2017-10-30 update

**Comment by ClairePA** [comment]
Brackets now affect the properties, but not the structure view. 
![image](https://user-images.githubusercontent.com/3986896/32218413-b504865a-be22-11e7-80d8-a67f9c919d07.png)
i.e. the same structure is show above and below.
![image](https://user-images.githubusercontent.com/3986896/32218438-bfd349a4-be22-11e7-9230-71c6e2411e91.png)

**Comment by scilligence** [comment]
Fix in 2017-11-20 update

**Comment by ClairePA** [comment]
Confirmed fixed. Thanks.
