### ISSUE TITLE
Monomer numbering should reset when groups are created

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#131]
When a group is formed out of part of a simple polymer that simple polymer is split into two. As the polymer is now split the numbering of the monomers should restart. 

![image](https://user-images.githubusercontent.com/3986896/31501269-ad0f0224-af61-11e7-9986-11dd09e59d70.png)

**Comment by scilligence** [comment]
Fixed in 2017-10-17 update

**Comment by ClairePA** [comment]
It still looks the same to me.

**Comment by ClairePA** [comment]
Now if I try to create a group it says that all monomers need to be in the same chain. 
![image](https://user-images.githubusercontent.com/3986896/31710250-572a4302-b3ec-11e7-9bee-e9bfa7c9553f.png)
![image](https://user-images.githubusercontent.com/3986896/31710270-63aa34c0-b3ec-11e7-8f4d-14e3be764dbb.png)

In this case the monomers are in a single chain.

**Comment by scilligence** [comment]
Fixed in 2017-10-24 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
