### ISSUE TITLE
Collapsing a group causes layout issues

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#132]
See below for an example. 

![image](https://user-images.githubusercontent.com/3986896/31501939-899d1fa4-af63-11e7-83b2-2250bcd3c0f1.png)
![image](https://user-images.githubusercontent.com/3986896/31501957-96ba1c14-af63-11e7-938c-0a1860bf1a55.png)

**Comment by scilligence** [comment]
Fixed in 2017-10-17 update

**Comment by ClairePA** [comment]
Confirmed fixed - close.
