### ISSUE TITLE
No validation on monomer position entries

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#133]
It is possible to add a number for the connection point to a monomer number that does not exist. See below;

![image](https://user-images.githubusercontent.com/3986896/31502902-29ce2638-af66-11e7-87c1-2bb3efa51a90.png)
The toolkit picks up this kind of error. 
![image](https://user-images.githubusercontent.com/3986896/31502929-383ee98c-af66-11e7-8b94-e33c59f4ce7c.png)

**Comment by ClairePA** [comment]
Validation can be done via a manual button on the canvas. 
The button should be the standard background colour to start, change to red if it fails validation, green if it passes.

**Comment by scilligence** [comment]
fixed in 2017-12-02 update.  But the valication web service should specified as below:

                    app = new scil.helm.App("div1", {
                        ...., validateurl: "Service.aspx?cmd=helm.validate",
                   });

**Comment by ClairePA** [comment]
I can't see a button and have checked that I have the correct version.

**Comment by scilligence** [comment]
Sorry.  It is in HELM tab

**Comment by ClairePA** [comment]
Ah, I have found it now thanks. 

However, you still need to call the current functionality using whatever the toolkit currently has implemented or change the back end to fit your call.

**Comment by scilligence** [comment]
So there are two service APIs should be exposed by the new Monomer Web Service: (1) convert SMILES into molfile (for bug #142); (2) validate a HELM

**Comment by scilligence** [comment]
Validate web service is implemented on the test page: http://54.91.164.146/HELM2MonomerService/hwe/examples/App.htm

**Comment by ClairePA** [comment]
Confirmed that the validation is present.
