### ISSUE TITLE
You can't add an annotation to a simple polymer

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#136]
The HELM2 notation allows annotations to be added at monomer, simple polymer and group levels. At present we can only add annotations at monomer level. The other levels must be implemented.

**Comment by scilligence** [comment]
Fixed in 2017-11-13.  Create a group first, then specify annotation by using context menu > Set Properties

**Comment by ClairePA** [comment]
Look fine. Thanks.
