### ISSUE TITLE
Ambiguous bond layout is confusing

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#137]
At present the bond attributes are displayed as below:

![image](https://user-images.githubusercontent.com/3986896/32542640-2a69a5c6-c46b-11e7-99f1-f31b25c1b84d.png)

This is confusing as it is difficult to tell the difference between the bond position and ratio. A better solution may be to use the group ratio for both connected and unconnected fragments. 

![image](https://user-images.githubusercontent.com/3986896/32542983-3e6f2338-c46c-11e7-9a99-d5a4b55dd2d9.png)

**Comment by scilligence** [comment]
Now the bond ratio displayed in a clear way. (2017-12-04 update)

**Comment by ClairePA** [comment]
Confirmed fixed.
