### ISSUE TITLE
Ratio information does not appear in the HELM string

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#139]
If I draw the following:

![image](https://user-images.githubusercontent.com/3986896/32544059-4e070902-c46f-11e7-86dc-812af1ba6f71.png)

The ratio of 2:3 does not appear in the HELM string.

**Comment by scilligence** [comment]
Fixed in 2017-11-13 update

**Comment by ClairePA** [comment]
The HELM has changed, but it does not include the ratio numbers.

![image](https://user-images.githubusercontent.com/3986896/32729793-dafeae80-c87c-11e7-92ec-58da8b8cf640.png)

**Comment by scilligence** [comment]
I don't think there should be a bond connecting the two if there is a ratio.

**Comment by ClairePA** [comment]
The ratio information is better recorded against the bond since it is possible to have multiple components connected and the approach above does not work well with more than two fragments. 

The UI should enforce the rule that ratios cannot be added to the group if the groups are connected by a bond.

**Comment by scilligence** [comment]
2017-12-09 update: ratio will be removed if the group is connected by a bond

**Comment by ClairePA** [comment]
Ratio information is removed if you change the ratio after drawing the bond, but drawing the bond does not remove existing ratio information. 

![image](https://user-images.githubusercontent.com/3986896/33839037-128df8c0-de89-11e7-9b79-1e41b2da8a6a.png)

Ironically the ratio information now does appear in the HELM string, so the original issue is fixed. Perhaps we should discuss tomorrow?

**Comment by scilligence** [comment]
decision from today's meeting:
------------------
When drawing a bond connecting the two group, their ratio should be cleared.

**Comment by scilligence** [comment]
Ratio number should be displayed as "ratio: 3"

**Comment by scilligence** [comment]
Fixed in 2017-12-13 update

**Comment by ClairePA** [comment]
Looks great and the warning message and change of text are good. Just one thing, only one of the ratios is cleared. 
![image](https://user-images.githubusercontent.com/3986896/33936722-6ea2f21c-dff8-11e7-82a8-46baa6fa26fe.png)

**Comment by scilligence** [comment]
Sorry.  there is typo.  Fixed in 2017-12-14 update.

**Comment by ClairePA** [comment]
Confirmed fixed.
