### ISSUE TITLE
I can't create a group containing peptide and oligo chains

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#140]
If I try to create a group of the following:

![image](https://user-images.githubusercontent.com/3986896/32730006-9850c8e2-c87d-11e7-82a9-2d7832e2156e.png)

I get this error message.

![image](https://user-images.githubusercontent.com/3986896/32730023-a8b80b3c-c87d-11e7-9104-f980b8b9889c.png)

It should be possible to create a group from different simple polymer types. (That was the original purpose of groups)

**Comment by scilligence** [comment]
No you cannot.  If yes, the monomer position in the group will be a problem. e.g. if you see position 1, it is hard to find which monomer this is.  And the same when using a monomer symbol.

**Comment by TianhongZhang** [comment]
Why do you want to put two connected chains into a group? They are covalently linked already. Groups are meant to put separate chains together and you can define their ratios.

**Comment by ClairePA** [comment]
OK, but you can't group unconnected chains either.

**Comment by ClairePA** [comment]
You can create a group from unconnected or unconnected chains by creating individual groups for each chain and then grouping the groups. 

This is the better way of solving the problem, therefore this issue should be closed.
