### ISSUE TITLE
Hydrogen pairing is recorded in section 3

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#141]
Hydrogen pairing is recorded in section 3. This is correct for HELM1, but HELM2 changed the location of hydrogen pairing information. See extract from section 5.3 of the specification below: 

_In HELM specification 1 and 1.1, the section number 3 was used for the list of hydrogen pairings instead of the polymer groups. The hydrogen pairings are now stored in the connection section (number 2) since hydrogen bonds are now recognized as a special form of connection._

**Comment by scilligence** [comment]
Fixed in 2017-12-1 update

**Comment by ClairePA** [comment]
Confirmed fixed. Thanks.
