### ISSUE TITLE
Collapsing a group removes the annotation from the HELM string

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#143]
I enter a peptide, create a group and add an annotation. 

![image](https://user-images.githubusercontent.com/3986896/33902629-8c48b5f8-df6d-11e7-8bd5-24e6f1a931cf.png)

if I then collapse the group, the annotation is lost from the HELM string. 

![image](https://user-images.githubusercontent.com/3986896/33902659-a99e70a2-df6d-11e7-8a9d-183c0d97a29c.png)

**Comment by scilligence** [comment]
Fixed in 2017-12-13 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
