### ISSUE TITLE
Sugar unknown monomer only has 2 connection points

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#145]
If I draw a molecule using the * sugar monomer I can't add a base as there are only 2 connection points available. 

![image](https://user-images.githubusercontent.com/3986896/33936978-745facda-dff9-11e7-96ff-a4da3df4c6bc.png)

![image](https://user-images.githubusercontent.com/3986896/33936987-7e26a2aa-dff9-11e7-91dd-55b1b5faf693.png)

**Comment by scilligence** [comment]
Fixed in 2017-12-14 update

**Comment by ClairePA** [comment]
Confirmed fixed.
