### ISSUE TITLE
Ambiguous bond information is only partially displayed

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#148]
If an ambiguous bond between groups has only some of the attributes defined, only the defined attributes are displayed. This is confusing. 

![image](https://user-images.githubusercontent.com/3986896/33988799-6df5ea84-e0bd-11e7-940a-513c4c89b0c8.png)

All attributes should be shown.

**Comment by scilligence** [comment]
Could you paste the HELM notation here?  I guess the missing information is not specified.  Thanks.

**Comment by ClairePA** [comment]
The HELM is:

PEPTIDE1{A.C.D.D.P.P}\|PEPTIDE2{A.C.D.D.P.P}$PEPTIDE1,PEPTIDE2,1:?-?:?$G3(PEPTIDE1+PEPTIDE2:2)$$V2.0

and the bond attributes are;

![image](https://user-images.githubusercontent.com/3986896/34489806-8ce3054a-efd5-11e7-9782-3d5cc4dbbb99.png)

So the display is correct, but confusing. It should show which attributes are not specified. 
Please note that the HELM notation says that if the ratio is not specified the proportion of that component is unknown and you cannot assume a value (e.g. 1).

**Comment by scilligence** [comment]
Fixed in 2018-01-08 update.   It is able to set the default ratio value by changing the value of this variable:

rg.helm.webeditor.defaultbondratio = null; // or ?, 1

**Comment by ClairePA** [comment]
Good start but there is some work to do before this is fully functioning. The main issues are;

- The display for group 1 and group 2 should match. If attributes are displayed for one then the other should also be displayed.  
- It must be possible to change a default value to nothing or ? without it reverting to the default. ? Is a valid value in the HELM notation
- Ratio values of 1:1 should not be displayed if the other values are not displayed. 
- Null values appear in the HELM for some of the attributes which is causing invalid HELM


  | Action | Value | Display | Preferred Display
-- | -- | -- | -- | --
1 | Draw bond | Position = ? | null |  
  |   | R# = ? | null |  
  |   | Ratio = 1 | Null |  
1 |   | Position = ? | null |  
  |   | R# = ? | null |  
  |   | Ratio = 1 | Null |  
  | HELM is invalid - see screenshots   below.Â |   |   |  
2 | Go into â€˜set   attributes' and make no changes. Exit 'set attributes'Â | Position = ? | null |  
  |   | R# = ? | null |  
  |   | Ratio = 1 | Ratio =1 | should be as action1 i.e. the   ratio should not be displayed.Â
2 |   | Position = ? | null |  
  |   | R# = ? | null |  
  |   | Ratio = 1 | Ratio =1 |  
3 | Go   into â€˜set attributes' and remove the 1 from the ratio. Save and then go back   into the 'set attributes' box. The ratio boxes have 1 in them again, this is   incorrect - it must be possible to specify an unknown ratio, either by   removing the 1 or by adding ?.Â |   |   |  
4 | Change the value of R# for the first   group to 1.Â | Position = ? | Pos:? |  
  |   | R# = 1 | R#: R1 |  
  |   | Ratio = 1 | Ratio =1 |  
4 |   | Position = ? | null | Pos:? Should be displayed
  |   | R# = ? | null | R# should be displayed
  |   | Ratio = 1 | Ratio =1 |  







![image](https://user-images.githubusercontent.com/3986896/34669225-a08393de-f468-11e7-975e-9ef1c121fef4.png)
![image](https://user-images.githubusercontent.com/3986896/34669245-acf6b902-f468-11e7-85b9-937633a70b93.png)

**Comment by scilligence** [comment]
Could you write down the steps on how to generate this help?
![image](https://user-images.githubusercontent.com/19560173/34688379-e5ca5bbe-f47f-11e7-8ad1-503326a711ba.png)

**Comment by ClairePA** [comment]
I can't reproduce the nulls, so please take this off the list of issues.

**Comment by scilligence** [comment]
fixed in 2018-01-10 update

**Comment by ClairePA** [comment]
The behaviour still looks the same to me. the issues identified in the comment above are still there. Please implement the changes described in the table and the list below:

- The display for group 1 and group 2 should match. If attributes are displayed for one then the other should also be displayed.
- It must be possible to change a default value to nothing or ? without it reverting to the default. ? Is a valid value in the HELM notation
- Ratio values of 1:1 should not be displayed if the other values are not displayed.
- Null values appear in the HELM for some of the attributes which is causing invalid HELM

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
Perfect! Many thanks.
