### ISSUE TITLE
It is possible to add letters to brackets

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#151]
Steps to reproduce:

- Draw brackets
- Type letters
- Click away from the bracket. 

The letters are displayed on the canvas and included in the HELM, but have no meaning. 
![image](https://user-images.githubusercontent.com/3986896/34516446-b6462964-f06e-11e7-962a-3b37a0ec5597.png)

![image](https://user-images.githubusercontent.com/3986896/34516452-bbee1228-f06e-11e7-8a9e-ab306001207d.png)

**Comment by scilligence** [comment]
So the change request is to only allow.  Please confirm.
1. *
2. A number, e.g. 09
3. A range, e.g. 12-23

**Comment by ClairePA** [comment]
Yes. Details also given in issue #126.

**Comment by scilligence** [comment]
Fixed in 2018-01-08 update

**Comment by ClairePA** [comment]
Perfect - thanks.
