### ISSUE TITLE
The navigation menu to the monomer and ruleset managers is not available

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#152]
I can't get the monomer and ruleset managers menu to appear in the latest version of the editor. 

![image](https://user-images.githubusercontent.com/3986896/34516576-4595d04c-f06f-11e7-9bbf-d4f85988c7a5.png)

**Comment by scilligence** [comment]
Sorry.  It is fixed now.

**Comment by ClairePA** [comment]
Confirmed fixed.
