### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#153]
The index.htm file contains links to https://pistoiaalliance.atlassian.net/wiki/display/PUB/Installation+guide which is broken

**Comment by ClairePA** [comment]
Sorry Yohann, is this in the HELMWebEditor repository? I think it may have moved, but can't find the index.htm file you are referring to.

**Comment by ClairePA** [comment]
Documentation has been updated. Close.
