### ISSUE TITLE
Link to zip file of home page to update

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#154]
The link for the zip file provided on the HELM editor GitHub page: https://github.com/PistoiaHELM/HELMWebEditor is to be updated.
https://github.com/PistoiaHELM/HELMWebEditor/releases/download/V1.0.0/HELMWebEditor1.0.0.zip is giving a 404 error message.

**Comment by ClairePA** [comment]
Zip files now seem to open. Yohann, please could you check?

**Comment by ClairePA** [comment]
Documentation has been updated. Close.
