### ISSUE TITLE
Link to Pistoia Alliance site link need to be updated

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#155]
On the home page of the GitHub HELM editor (https://github.com/PistoiaHELM/HELMWebEditor) the link to 
https://pistoiaalliance.atlassian.net/wiki/display/PUB/New...+HELM+web-editor should be https://pistoiaalliance.atlassian.net/wiki/spaces/PUB/pages/35028994/HELM+Web-editor

**Comment by ClairePA** [comment]
Looks like it has changed - Yohann, please could you check and close if happy?

**Comment by ClairePA** [comment]
Documentation has been updated. Close.
