### ISSUE TITLE
Can't create a new monomer

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#156]
If I create a new monomer using the monomer manager and click OK, I get a 404 error. 

![image](https://user-images.githubusercontent.com/3986896/35287590-970359a4-005a-11e8-8f5a-2cce0a656a2f.png)

**Comment by scilligence** [comment]
It looks like the problem is in Monomer Web Service side.  Here is message I got now:

![image](https://user-images.githubusercontent.com/19560173/35289795-5ea6b44e-0036-11e8-84f6-fef5f47cba3c.png)

**Comment by MarkusWeisser** [comment]
The latest release of the monomer service has an updated Swagger page with the body parameter. Could you please try this. The following JSON works on my side:

{
	"symbol": "Test1",
	"name": "Test2",
	"molfile": "xxx",
	"author": "UnknownAuthor",
	"id": 0,
	"rgroups": [{
		"id": 0,
		"alternateId": null,
		"label": "R3",
		"capGroupName": "X",
		"capGroupSMILES": null
	}],
	"smiles": "cccccc",
	"monomerType": "Undefinded",
	"naturalAnalog": "X",
	"polymerType": "CHEM",
	"createDate": "Thu Jan 25 11:16:17 CET 2018"
}

Please have in mind that SMILES and MOLFILE have to be unique!

**Comment by ClairePA** [comment]
I have tried saving a new monomer since the service was updated and I do not get an error when I create a monomer, but the monomer is not listed once I have saved it. 

I get no feedback when I click the save button, which makes me think that clicking "save" is not doing anything.

**Comment by scilligence** [comment]
Which URL do you use?  You might want to update hwe folder by downloading the new version from here: https://github.com/PistoiaHELM/HELMWebEditor/releases

**Comment by ClairePA** [comment]
I use the webeditor test site you set up at http://54.91.164.146/HELM2MonomerService/hwe/examples/MonomerLibApp.htm.

**Comment by scilligence** [comment]
Markus, I got null in Response if trying to create a new CHEM.  Is it possible to return any error message if failed:

![image](https://user-images.githubusercontent.com/19560173/35588922-1cf05c3c-063d-11e8-9c2e-4bda0d22bd76.png)

![image](https://user-images.githubusercontent.com/19560173/35588939-291c63d4-063d-11e8-854e-0dccec2ef922.png)

**Comment by ClairePA** [comment]
Tony - can you check the format of the JSON as it includes R groups listed separately as well as in the array? Only the array should be used.
Quattro are working on additional error messages.

**Comment by scilligence** [comment]
I upgrade HELM2MonomerService.war to release 7.  It looks like it works now.

**Comment by ClairePA** [comment]
I still can't create a new monomer using the test version. Has this been updated? I get no error message, but the new monomer is not there.

**Comment by ClairePA** [comment]
Monomer is now created. Close.
