### ISSUE TITLE
If I try to save monomers as an sdf I get an error

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#157]
![image](https://user-images.githubusercontent.com/3986896/35388066-34612792-01ca-11e8-8c1d-0f0db83d58b5.png)

![image](https://user-images.githubusercontent.com/3986896/35388015-03d76794-01ca-11e8-9571-2d974c854ca5.png)

**Comment by scilligence** [comment]
We need new web service APIs in Monomer Web Service for following tasks:

1.	Download all monomers as sdf/json
2.	Import monomers from a file sdf/json

**Comment by ClairePA** [comment]
Postpone until the next phase.

**Comment by scilligence** [comment]
The toolbar options are hidden now for this release

**Comment by ClairePA** [comment]
Confirmed hidden.
