### ISSUE TITLE
Deleting a monomer creates an error message

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#158]
I opened the monomer record for 3SS6, clicked delete and I got the following error:

![image](https://user-images.githubusercontent.com/3986896/35615862-57b2ede8-066b-11e8-93ef-90fe53ee895c.png)

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
