### ISSUE TITLE
Natural analogue is mandatory but misses a star

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#159]
In the monomer page, when adding a new RNA monomer, the natural analogue is mandatory but there is no red star next to title.

**Comment by scilligence** [comment]
It is mandatory for RNA, and Peptide, but not for CHEM.

**Comment by ClairePA** [comment]
Difficult to find a better alternative solution since it is only mandatory in some circumstances. Close.

**Comment by ClairePA** [comment]
My mistake - it is mandatory, so a star needs to be in place.

**Comment by ClairePA** [comment]
Star now present. Close.
