### ISSUE TITLE
In-line HELM monomers are not connected

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#160]
I can enter the following HELM string
`PEPTIDE1{A.[*C(=O)[C@H](C)N(*)C |$_R2;;;;;;_R1;;;$|].A}$$$$V2.0`

but the in-line monomer is not connected to anything. 

![image](https://user-images.githubusercontent.com/3986896/36438863-08a08712-1663-11e8-9154-92dc074195aa.png)

**Comment by scilligence** [comment]
Web Editor depends on HELM Web Service to convert the smiles into molfile.  But the web services doesn't return R1/R2.  The web service is: 

http://54.91.164.146/WebService/service/Conversion/Molfile

And it returns:

`
  CDK     0222181427

  8  7  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 *   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990   -2.2500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.5981   -0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
    2.5981    1.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8971   -0.7500    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.8971   -2.2500    0.0000 *   0  0  0  0  0  0  0  0  0  0  0  0
    5.1962   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0 
  2  3  2  0  0  0  0 
  2  4  1  0  0  0  0 
  4  5  1  6  0  0  0 
  4  6  1  0  0  0  0 
  6  7  1  0  0  0  0 
  6  8  1  0  0  0  0 
M  END
`

**Comment by ClairePA** [comment]
Hi Markus, 

is this something you could look at?

**Comment by MarkusWeisser** [comment]
Square brackets are currently mandatory around the * symbol. 
If you paste the following HELM into the editor:
PEPTIDE1{A.[[*]C(=O)[C@H](C)N([*])C |$_R2;;;;;;_R1;;;$|].A}$$$$V2.0

this will be automaticall converted into 
PEPTIDE1{A.[[[R1]]C(=O)[C@H](C)N([R2])C].A}$$$$V2.0

but editor is not able to show the structure again. I guess the two square brackets around R1 are the problem. Manually removing one square bracket around R1 gives correkt structure. Is the conversion done by toolkit?

**Comment by scilligence** [comment]
Markus, could you wrap the HELM string in GitHub code format?  Otherwise the text is escaped.  Thanks.

**Comment by scilligence** [comment]
I guess Markus is using this HELM string:

`PEPTIDE1{A.[[*]C(=O)[C@H](C)N([*])C |$_R2;;;;;;_R1;;;$|].A}$$$$V2.0`

**Comment by ClairePA** [comment]
Which takes us back to Roger's point that using [*] is invalid SMILES notation. If I change to:
PEPTIDE1{A.[[*:2]C(=O)[C@H](C)N([*:1])C |$_R2;;;;;;_R1;;;$|].A}$$$$V2.0
I get
![image](https://user-images.githubusercontent.com/3986896/36601439-037c93a6-18ad-11e8-9b00-9a155031c7a4.png)
which is even better than the structure in the comment above. 

Should we just outlaw using * by itself? The problem goes away then.

**Comment by ClairePA** [comment]
Retested. The test HELM string still results in disconnected monomers.

**Comment by MarkusWeisser** [comment]
The example no. 3 is missing a pair of brakets: PEPTIDE1{A.[*C(=O)[C@H](C)N(*)C |$_R2;;;;;;_R1;;;$|].A}$$$$V2.

Beside that, all examples are valid in toolkit and generated structure images look good.

**Comment by ClairePA** [comment]
I am using http://54.83.135.171/WebService/FirstPage.html and the images are still wrong. 

Tony, can you check that the latest version of the webservices are being used on this site please?

Thanks.

**Comment by ClairePA** [comment]
See circulated spreadsheet for expected behaviour.

**Comment by ClairePA** [comment]
Duplicate of #210. Close here and continue the discussion on that issue.
