### ISSUE TITLE
HELM created for blobs is invalid

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#161]
The HELM is created for directly connected blobs is invalid. See below for an example. 

Invalid HELM generated
`BLOB1{Bead}|PEPTIDE1{A.C.L}$PEPTIDE1,BLOB1,1:R1-1:?$$$V2.0`

This is what it should be. 
`BLOB1{Bead}|PEPTIDE1{A.C.L}$PEPTIDE1,BLOB1,1:R1-?:?$$$V2.0`

**Comment by scilligence** [comment]
Fixed 2018-02-22

**Comment by ClairePA** [comment]
Confirmed fixed.
