### ISSUE TITLE
Link to the demo site is wrong

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#170]
The demo site is at http://webeditor.openhelm.org/hwe/examples/App.htm

At one point during testing http://webeditor.openhelm.org/hwe would take you directly to the editor. I would like http://webeditor.openhelm.org/hwe to be link as it is simpler.

**Comment by scilligence** [comment]
Fixed in 1.1.1.zip file: using redirection

**Comment by ClairePA** [comment]
Just curious - why redirect? Isn't it just as easy to go direct? I find pages that redirect irritating.

**Comment by ClairePA** [comment]
Update - we would like the link to be  http://webeditor.openhelm.org with no redirection.

**Comment by ClairePA** [comment]
The complexity of the URL caused some confusion with users in Novartis during their deployment. It would be better if the landing page was a route index page.

**Comment by ClairePA** [comment]
Postponing this issue as it is unlikely we will make progress on it.
