### ISSUE TITLE
Seaching on Symbol or name in the monomer manager returns nothing

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#174]
If I type the symbol of a monomer that I know exists in the list such as R or A, nothing is shown in the monomer list. The matching monomers should be listed. 

Not sure where the issue is, but assigning to Markus to investigate. Please reassign if this is a front end issue.

**Comment by scilligence** [comment]
Markus,

Here is the GET query sent to the web service.  Could you let me know how it should be formatted?  Thanks.

Request URL: http://54.91.164.146/HELM2MonomerService/rest/monomer/ALL?limit=10&offset=0&filter=Test&filterField=name&polymertype=&monomertype=&symbo

**Comment by MarkusWeisser** [comment]
This is the cURL:
curl -X GET "http://54.91.164.146/HELM2MonomerService/rest/monomer/ALL?monomertype=Backbone&filter=A&limit=10&offset=0" -H  "accept: application/json"

And this is the Swagger example:

![grafik](https://user-images.githubusercontent.com/6429669/38873725-b8b1ad42-4256-11e8-914c-d91c8dd0a2e4.png)

**Comment by scilligence** [comment]
Fixed in 2018-05-01 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
