### ISSUE TITLE
Import SMILES in monomer manager does not work

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#177]
When trying to create a new monomer, I can import a mol file to get the structure but importing a SMILES fails.
See attached video.

[2018-04-20_12-44-39.mp4.zip](https://github.com/PistoiaHELM/HELMWebEditor/files/1932904/2018-04-20_12-44-39.mp4.zip)

**Comment by scilligence** [comment]
SMILES is not supported.  The option is removed in 2018-05-01 update

**Comment by ClairePA** [comment]
Transferred to issue#194. Close here.
