### ISSUE TITLE
Webservices do not cap in-line SMILES

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#178]
The following HELM

`PEPTIDE1{C.G.[[*]N[C@@H](C=O)C([*])=O |$_R1;;;;;;_R2;$|]}$$$$V2.0`
Does not generate the correct mol formula. The un-substituted R group is not changed into the capping group. 

![image](https://user-images.githubusercontent.com/3986896/39134556-c3e2db34-470e-11e8-85fc-5be14c792dc5.png)

**Comment by MarkusWeisser** [comment]
Where is the capping group defined?

**Comment by MarkusWeisser** [comment]
I guess it makes sense to not calculate molecular properties from not fully defined structures. I would not recommend to use default values für capping groups. 
The user should modify the inline SMILES for a fully defined molecule.

**Comment by ClairePA** [comment]
The HELM team agreed that mol properties should not be calculated for structures with free connection points. This issue is continued via the spreadsheet of in-line HELM test structures. CLose here.
