### ISSUE TITLE
Editor does not allow a CHEM in-line HELM that should be valid

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#179]
I used the following HELM string
`CHEM1{[[*:2]C(=O)[C@H](C)N([*:1])CC]}$$$$`

The webservices believe it is valid and can perform all calculations correctly, however the webeditor does not accept it. 

![image](https://user-images.githubusercontent.com/3986896/39178333-5b6e03bc-47a9-11e8-942c-e71b4f90cb83.png)

**Comment by scilligence** [comment]
Fixed in 2018-05-01 update

**Comment by ClairePA** [comment]
Confirmed fixed.
