### ISSUE TITLE
Cyclic peptide HELM is not correct

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#180]
I drew the following peptide into the webeditor:

![image](https://user-images.githubusercontent.com/3986896/39179315-e7f03aa6-47ab-11e8-997e-ef9f72cfb283.png)

The HELM generated is 
`PEPTIDE1{L.M.P.Q.R.S.T}$undefined,undefined,undefined:Rundefined-undefined:Rundefined$$$V2.0`
The undefined descriptions should be removed as it is a simple backbone connection. The correct HELM is

`PEPTIDE1{L.M.P.Q.R.S.T}$PEPTIDE1,PEPTIDE1,7:R2-1:R1$$$`

**Comment by scilligence** [comment]
Fixed in 2018-05-01 update

**Comment by ClairePA** [comment]
Confirmed fixed.

**Comment by SapSci** [comment]
We are running into this exact issue with the 2019 release, and have verified it also happens on the editor demo site. Does the fix need to be reapplied to the latest release?
