### ISSUE TITLE
Brackets in a HELM string are not transferred to the graphical depiction

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#181]
I draw a HELM molecule and put brackets around one of the monomers. The correct HELM is generated. 

![image](https://user-images.githubusercontent.com/3986896/39200340-d3fc61c2-47e3-11e8-8077-084087d619fb.png)

I then:

- copy the HELM 
- clear the screen
- paste the same HELM into the box 
- click 'apply', 

The bracket is removed from the string and the picture shows the molecule without the brackets. 

![image](https://user-images.githubusercontent.com/3986896/39200420-023417ba-47e4-11e8-890f-e4161714277e.png)

**Comment by scilligence** [comment]
Fixed 2018-05-06 update

**Comment by ClairePA** [comment]
Confirmed fixed.
