### ISSUE TITLE
The webservices will not calculate properties for molecules with brackets

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#182]
The molecule PEPTIDE1{A.G.A.C'5'.A}$$$$V2.0 is fully defined and it should be possible to calculate a mol weight, formula and canonical SMILES. however the webservices generate an error.

![image](https://user-images.githubusercontent.com/3986896/39200739-e1dd561a-47e4-11e8-894e-62a50d4f5db1.png)

**Comment by MarkusWeisser** [comment]
Toolkit is not able to create SMILES or Molfile from HELM with repeating units. So, molecular properties cannot be calculated.

**Comment by ClairePA** [comment]
Why is there a problem with it creating the SMILES or molfile? It shoudl be possible no?

**Comment by ClairePA** [comment]
DIscussed with Yohann. Novartis are having to export to an external tool to work around this problem. It would be great to have it fixed.

**Comment by ClairePA** [comment]
Tested and the webeditor seems to work OK, but the webservices page still gives me an error. 
![image](https://user-images.githubusercontent.com/3986896/45230439-c5651080-b2c0-11e8-8c34-d2a4979e4659.png)

**Comment by ClairePA** [comment]
Retested and it is fine now. Close.
