### ISSUE TITLE
In-line HELM SMILES is not recognised by the editor

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#185]
The HELM string: `CHEM1{[*SCCCC=1C=CC=CC1|]}$$$$` is valid according to the webservices and the webservices can generate the molecule properties. However, the editor does not accept it. 

![image](https://user-images.githubusercontent.com/3986896/39249202-04289cfa-4896-11e8-9745-d230a075f3d9.png)

**Comment by scilligence** [comment]
Recommend to modify the smiles: 
`CHEM1{[[*:1]SCCCC=1C=CC=CC1]}$$$$`

**Comment by ClairePA** [comment]
The odd thing, is that 
`RNA1{R.([*n1cnc2c1nc(nc2N)Cl |$_R1;;;;;;;;;;;$|])}$$$$` is accepted fine, even without the square brackets. 

So why is `CHEM1{[*SCCCC=1C=CC=CC1|]}$$$$` different?

**Comment by scilligence** [comment]
The first one has the star defined as R1, but the second one doesn't

**Comment by ClairePA** [comment]
Sorry - my mistake.
