### ISSUE TITLE
Repeating single CHEM monomer is incorrectly invalid

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#188]
Single monomers with brackets are valid and accepted by the webeditor.

`PEPTIDE1{A'11'}$$$$V2.0`
![image](https://user-images.githubusercontent.com/3986896/39308954-bbf6067e-495e-11e8-8f63-f0770bb6a807.png)

but I draw the following
![image](https://user-images.githubusercontent.com/3986896/39309145-3415f60a-495f-11e8-9199-7d5657cddb58.png)

the correct HELM is generated `CHEM1{[Az]'11'}$$$$V2.0` and the HELM a molecule properties are calculated. 

However, if I clear the editor and paste in the HELM string `CHEM1{[Az]'11'}$$$$V2.0` and click Apply, only one monomer is displayed:
![image](https://user-images.githubusercontent.com/3986896/39309246-735e3d9a-495f-11e8-9ef8-7985a8d3a99c.png)
 and the HELM string is changed to `CHEM1{[Az]}$$$$V2.0`

The webservices state that `CHEM1{[Az]'11'}$$$$V2.0` is invalid HELM.

**Comment by MarkusWeisser** [comment]
Repeating units cannot be used with CHEM monomers, only with RNA or PEPTIDE monomers. The reason for that is that CHEM monomers have not a defined connection order (R1 goes to R2) for automatically creating polymers. This should be mentioned in the HELM specification and the Editor should show the parser error.

**Comment by ClairePA** [comment]
Thanks Markus - you are completely right. 

I have updated the spec. The issue about the editor showing the parser error is wider than just this issue and will be taken up elsewhere.
