### ISSUE TITLE
Incorrect structure generated for repeating units

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#189]
I draw the following:
![image](https://user-images.githubusercontent.com/3986896/39312095-8d8f6192-4966-11e8-946c-eead6328228f.png)

The structure is hard to see:
![image](https://user-images.githubusercontent.com/3986896/39312113-9ec3e76c-4966-11e8-807a-d9077ca0d522.png)
and generates the following molfile. 
```
   JSDraw204261815252D

 12 11  0  0  1  0              0 V2000
   16.2010   -7.4359    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.5519   -8.2160    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.9030   -7.4361    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.5518   -9.7759    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   18.9031   -5.8761    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   16.2010  -10.5559    0.0000 R#  0  0  0  0  0  0  0  0  0  0  0  0
   21.6054   -5.8765    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   21.6050   -7.4366    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   22.9559   -8.2167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.2540   -8.2161    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   24.3070   -7.4372    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   22.9556   -9.7768    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  1  0  0  0
  4  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  5  2  0  0  0  0
  3 10  1  0  0  0  0
  4  6  1  0  0  0  0
  8  7  1  1  0  0  0
 10  8  1  0  0  0  0
  8  9  1  0  0  0  0
  9 11  2  0  0  0  0
  9 12  1  0  0  0  0
A    6
R1
M  RGP  1   6   1
M  END

```
and SMILES is `C[C@H](N[H])C(=O)N[C@@H](C)C(=O)N[C@@H](C)C(=O)O.C[C@H](N*)C(=O)O`

importing into PubChem Sketcher and moving the overlapping atoms gives:

![image](https://user-images.githubusercontent.com/3986896/39312619-ed4d6b8c-4967-11e8-9083-da3e9e2ac4ec.png)

So one of the repeating units is not attached.

**Comment by ClairePA** [comment]
Why not? They are exact structures and should be generated.

**Comment by ClairePA** [comment]
Please would you change the toolkit to generate the SMILES and molfile from HELM with repeating units?

**Comment by ClairePA** [comment]
Discussed with Yohann. Novartis are interested in using repeating units and would prefer this to be fixed.

**Comment by ClairePA** [comment]
Retested and the issue is still present.

**Comment by AnneMund** [comment]
I cannot reproduce the issue; if I try out the image generation on the WebService side for PEPTIDE1{A.D'2'.C.F}$$$$V2.0, I get the following: 
![grafik](https://user-images.githubusercontent.com/34510755/46276498-93ae3500-c560-11e8-8cfa-59d85534fd8a.png)

If I generate SMILES instead and put them into the PubChem Sketcher, I get 
![grafik](https://user-images.githubusercontent.com/34510755/46276444-65305a00-c560-11e8-9653-01a62043a87c.png)
which results in
![grafik](https://user-images.githubusercontent.com/34510755/46276513-9e68ca00-c560-11e8-801e-5be17afb1694.png)

Could it be that the re-test happended with an older version of the WebService still in place?

**Comment by ClairePA** [comment]
It looks like you are right. When I test on http://54.83.135.171/WebService/FirstPage.html I get the right structure, but if I use the webeditor on the same server I get disconnected structures. 
![image](https://user-images.githubusercontent.com/3986896/46283948-ee01c280-c56d-11e8-9343-806ee189c43c.png)
So, the conclusion is that the webservices are now working correctly, but the webeditor is creating its own structure and it is resulting in disconnected structures. 

Reassigning this issue to Tony.

**Comment by ClairePA** [comment]
Actually I have retested with more examples and the webservices version works for peptides, but not for CHEM and RNA. Try the examples below:
`CHEM1{[Az]'11'}$$$$V2.0`
`RNA1{R'11'}$$$$V2.0`
So both the webeditor and the webservices still need fixing.

**Comment by ClairePA** [comment]
Converting these issues into new separate issue logs as there are several things going on. Closing this log.
