### ISSUE TITLE
HELM is not generated correctly for CHEM polymer with more than one monomer

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#193]
I draw the following:

![image](https://user-images.githubusercontent.com/3986896/39479793-3587c25e-4d5e-11e8-8891-4e98cc1394c5.png)

The structure is generated correctly, but the HELM is incorrect. 

![image](https://user-images.githubusercontent.com/3986896/39479934-a519f2ea-4d5e-11e8-95f3-990c700074d6.png)

![image](https://user-images.githubusercontent.com/3986896/39479948-ad493516-4d5e-11e8-97b0-9809fc6ae095.png)

The HELM should be
`CHEM1{[SMCC]}|CHEM2{[EG]}$CHEM1,CHEM2,1:R1-1:R1$$$` (as you can't have a CHEM simple polymer with more than one monomer.)

You can type in the HELM and generate the correct structure, but not draw it on the canvas and generate the HELM.

**Comment by scilligence** [comment]
Is *EG* another chem monomer?  I cannot reproduce it using SMCC with chem monomers.

**Comment by ClairePA** [comment]
It is another CHEM monomer, but doesn't appear in the latest version of the editor as we have swopped to the monomer.org set. 
It is odd. I was definitely having problems before, but it looks fine now.
Propose close.
