### ISSUE TITLE
Webeditor thinks a group is a blob

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#195]
I draw a 2 monomer peptide, create a group and link a CHEM to the group.
![image](https://user-images.githubusercontent.com/3986896/39483378-11432dd2-4d6a-11e8-81a1-21119eb9e9b7.png)

If I right-click where the bond attaches to the outside of the group, I get the blob menu

![image](https://user-images.githubusercontent.com/3986896/39483353-fef99b16-4d69-11e8-92c9-411bce5e0266.png)

This should not be available as the group is not a blob.

**Comment by scilligence** [comment]
Fixed in 2018-05-06 update

**Comment by ClairePA** [comment]
Confirmed fixed, however I can no longer access the context menu for the bond between group and CHEM or the context menu for the group as a whole. I will raise these as separate issues.
