### ISSUE TITLE
Confirmation box after clicking 'new' is irritating

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#197]
If I choose to clear the canvas by clicking on 'new' I am asked if I am sure.

![image](https://user-images.githubusercontent.com/3986896/39517770-c471161a-4df8-11e8-85de-0f0b10b32691.png)
This is annoying and unnecessary since I can always choose to undo if I change my mind.

**Comment by scilligence** [comment]
Fixed 2018-05-06 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
