### ISSUE TITLE
Collapsing a group affects the mol wt and formula

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#198]
I use the following HELM string:
`PEPTIDE1{A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.C.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E}|PEPTIDE2{G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.C.S.S.S.S.S.S.S.S.S.P.P.P.P.P.P.P.P.P.K.K.K.K.K.K.K.K.K.K.K.K.K}|CHEM1{[PEG2]}|CHEM2{[SMCC]}$PEPTIDE1,CHEM1,C:R3-1:R1|PEPTIDE2,CHEM2,C:R3-1:R1$G1(PEPTIDE1+CHEM1:2.5)|G2(PEPTIDE2+CHEM2:1.5)$$`
![image](https://user-images.githubusercontent.com/3986896/39518200-23916054-4dfa-11e8-9a33-e8907b7fec3d.png)

and see the following properties which look like the mol wts and formulae of the CHEM monomers only.
![image](https://user-images.githubusercontent.com/3986896/39518114-d1147dac-4df9-11e8-9896-f35a3220e551.png)

If I expand the group I see a larger mol wt and formula.
![image](https://user-images.githubusercontent.com/3986896/39518236-3e1930e6-4dfa-11e8-86b5-ddbd008259a0.png)

Expanding or collapsing groups should not affect the mol wt and formula.

**Comment by scilligence** [comment]
Fixed now.

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
