### ISSUE TITLE
Cys-Cys bond is not retained after copying HELM into editor

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#201]
Steps to reproduce.

Enter the `PEPTIDE1{A.R.C.A.A.K.T.C.D.A}$PEPTIDE1,PEPTIDE18:R3-3:R3$$$` into the webeditor.
Click apply
The structure displayed is:
![image](https://user-images.githubusercontent.com/3986896/39580166-6d3cac40-4ee0-11e8-8983-5fc69f0d9824.png)
and the HELM is changed to `PEPTIDE1{A.R.C.A.A.K.T.C.D.A}$$$$V2.0`
I draw a bond between the Cys monomers and get the structure I was originally expecting:
![image](https://user-images.githubusercontent.com/3986896/39580225-936c2148-4ee0-11e8-8e00-b48b00948e2b.png)
with the correct, but slightly different HELM
`PEPTIDE1{A.R.C.A.A.K.T.C.D.A}$PEPTIDE1,PEPTIDE1,3:R3-8:R3$$$V2.0`

If I clear the editor and enter the generated HELM again `PEPTIDE1{A.R.C.A.A.K.T.C.D.A}$PEPTIDE1,PEPTIDE1,3:R3-8:R3$$$V2.0` I get the correct structure.

It should be possible to define the Cys-Cys bond as either `3:R3-8:R3` or `8:R3-3:R3`. Both are valid HELM and should be acceptable.

**Comment by scilligence** [comment]
There is a "," is missing between PEPTIDE1 and 8:

`PEPTIDE1{A.R.C.A.A.K.T.C.D.A}$PEPTIDE1,PEPTIDE18:R3-3:R3$$$`

**Comment by ClairePA** [comment]
Ah oops. Embarrassed face.
