### ISSUE TITLE
Applying a HELM string appears to do nothing until the resize bar is moved

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#203]
I paste the HELM string `CHEM1{[Az]}|PEPTIDE1{L.M}|RNA1{R(C)P.R(A)P}$RNA1,PEPTIDE1,6:R2-1:R1|PEPTIDE1,CHEM1,2:R2-1:R1$$$V2.0` into the HELM box and click apply. 

Nothing appears on the canvas. 

If I move the bar to resize the canvas the structure appears:

![image](https://user-images.githubusercontent.com/3986896/40357257-824ae12e-5db3-11e8-8e6f-75a801f0c98b.png)

If I use a simpler HELM string like `RNA1{R(U)P.R(T)P.R(G)P.R(C)P.R(A)}$$$$` I don't see this problem.

**Comment by scilligence** [comment]
Fixed in 2018-06-03 update

**Comment by ClairePA** [comment]
Confirmed fixed. Thanks.
