### ISSUE TITLE
IMPORTANT searching monomers in the monomer manager is broken

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#204]
At present there are two boxes for searching in the monomer manager

![image](https://user-images.githubusercontent.com/3986896/40795973-872d1672-64fb-11e8-82e2-7bf6225eeeb1.png)

- The symbol box does not work at all. 
- The name boxes performs a contains search against both symbol and name. 

I see from the Swagger that there is only one webservice for searching against name and it searches against both name and symbol. 

I would prefer that there were separate searches for symbol and name and we developed appropriate webservices to support this, however, in the meantime, can we put a temporary fix in place?
Please can we combine the symbol and name boxes in the UI and make it clear that they search both fields?

**Comment by scilligence** [comment]
Markus,

Could you check if this is correct?

Here are the queries:

1. Search by Name, which works:
http://54.83.135.171/HELM2MonomerService/rest/monomer/ALL?limit=10&offset=0&filter=25&polymertype=&monomertype=&symbol=&name=25&countperpage=

2. Searc by Symbol, which doesn't:
http://54.83.135.171/HELM2MonomerService/rest/monomer/ALL?limit=10&offset=0&filter=25&filterField=symbol&polymertype=&monomertype=&symbol=25&name=&countperpage=

**Comment by MarkusWeisser** [comment]
Yes, there was an issue with symbol search. Fixed in latest release:
https://github.com/PistoiaHELM/HELMMonomerService/releases/tag/1.0.2

**Comment by ClairePA** [comment]
Tested in latest version. Confirmed search is working perfectly.
