### ISSUE TITLE
New rule added to ruleset is not accessible in canvas

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#211]
Hi, 

I added a new rule in http://54.83.135.171/HELM2MonomerService/hwe/examples/RuleSetApp.htm (replace P by sP). It is saved correctly, but I cannot see this new ruleset from the canvas (app page) and rule tab.

**Comment by ClairePA** [comment]
This sounds like a similar problem to the monomer refresh issue. Can we put in a fix similar to the monomer fix where the webservices update the set of rules on creation of a new rule.

**Comment by scilligence** [comment]
Fixed now,  in javascript side

**Comment by ClairePA** [comment]
Retested and looks fixed to me. Yohann - could you check and close if you are happy?

**Comment by ypotier** [comment]
It looks good: the rule is now visible from the canvas as expected.
However, it introduced a new bug when create a rule with quote. Where the single quote symbol is added and create an error when trying to apply the rule. I am creating a new ticket for it so this one can be closed.
