### ISSUE TITLE
Users should not be able to specify the R group number for * monomers

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#213]
I create a short peptide AC
![image](https://user-images.githubusercontent.com/3986896/44036576-050a238a-9f0a-11e8-810e-2b41ac6e644e.png)
I then place a chem * monomer on the canvas and try to connect it to the peptide. 
I am asked whether I want to connect R1 or R2.
![image](https://user-images.githubusercontent.com/3986896/44036731-6d730158-9f0a-11e8-8a65-dd9691533f03.png)
A * CHEM monomer does not have any specified R groups, therefore any bond to it should be ambiguous and the HELM for this molecule should be:
`CHEM1{*}|PEPTIDE1{A.C}$PEPTIDE1,CHEM1,2:R2-1:?$$$V2.0`
The webeditor will accept this HELM, but does not generate it. 

RNA and PEPTDIDE * monomers should have R1 and R2, so they can form part of the backbone of these polymers, but CHEM should not.

**Comment by ClairePA** [comment]
Update from the team meeting discussion. 

The editor should not present options to connect a * monomer using a numbered R group. All connections to * monomers should be defined as ? The following illustrates this:

`PEPTIDE1{*}|PEPTIDE2{A.C}$PEPTIDE1,PEPTIDE2,1:?-?:?$$$V2.0 is valid`

`PEPTIDE1{*}|PEPTIDE2{A.C}$PEPTIDE1,PEPTIDE2, 1:R1-?:?$$$V2.0 is not valid`

However * can still be part of a simple backbone:

`PEPTIDE1{A.C.*}$$$$V2.0 is valid`

The editor should not present the user with a box to select R groups for * monomers. It should only allow ? to be assigned. Please change the editor so it does this.

**Comment by scilligence** [comment]
I made some change accordingly.  But if it don't distinguish R1/R2, web editor cannot tell this is backbone or not.

**Comment by ClairePA** [comment]
Retested and it looks OK. 
I see the problem with it recognising * as part of the backbone. Actually, since * represents a part of the structure that is unknown, it may be acceptable for it to be a new simple polymer strand. I think we should leave it as it is and see if there are major objections from users.
