### ISSUE TITLE
Additional quote symbol is added to rule when saving

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#214]
I created a new rule copied from existing rule for replacement:
`
function(plugin){
    var n = plugin.replaceMonomer(org.helm.webeditor.HELM.BASE, 'P','sP');return n>0;
}
`
You can see it on the screenshot:
![image](https://user-images.githubusercontent.com/8645925/44037676-e07db418-9ee2-11e8-9a7e-07fa2a8328ad.png)

after being saved, you can see the following code with additional quote around the monomer codes:
![image](https://user-images.githubusercontent.com/8645925/44037598-b65d5576-9ee2-11e8-9274-f69c84c03e5a.png)

When trying the apply that rule, these new quote symbol cause an error message:
![image](https://user-images.githubusercontent.com/8645925/44037623-c4bf700e-9ee2-11e8-9166-75678a71a36e.png)

this issue does not exist with the other replacement script using single quote. I also tried editing the code but the new quote symbol are still added.

**Comment by scilligence** [comment]
I believe this is an issue on the server side.  

Markus, could you check it out?

**Comment by ClairePA** [comment]
I believe the quote issue has been resolved. Yohann, please can you check?

**Comment by ypotier** [comment]
This issue is fixed
