### ISSUE TITLE
Cannot edit rules

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#222]
When trying to edit an existing rule, the following error message is displayed:
`Unable to load /HELM2MonomerService/rest/rule status: 409`

**Comment by scilligence** [comment]
1. This error is fixed in 2018-10-08

2. The HELM Monomer Webservice doesn't have Update method:  http://54.83.135.171/HELM2MonomerService/

**Comment by ypotier** [comment]
If there is no no update method, the 'edit/pen' icon is confusing.
I assume we cannot use the 'PUT' method to update existing rule?

**Comment by ClairePA** [comment]
Tony - can you try this out and let us know how it goes please?

**Comment by scilligence** [comment]
Fixed in 2018-10-15 update

**Comment by ClairePA** [comment]
OK, now there are two different modification situations. 

1) if you change the rule name, a new rule is created by the old rule stays there. The user is not warned that this is the case and it will be confusing. The old rule name should be deleted. 

2) if you change the description I still get the 409 error. 

![image](https://user-images.githubusercontent.com/3986896/46977513-4daab280-d0c4-11e8-86c1-724d5991517a.png)

**Comment by ClairePA** [comment]
Retested. Confirmed fixed.

**Comment by ypotier** [comment]
@ClairePA , I was able to change the description without error on the current version
