### ISSUE TITLE
Cannot delete rule

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#223]
when trying to delete an existing rule using the rule editor, the following error message is displayed:
`Unable to load /HELM2MonomerService/rest/delete/undefined/undefined status: 404`

**Comment by ClairePA** [comment]
The rest service seems to work OK. Is the web-editor calling the service via the name rather than the ID?

**Comment by scilligence** [comment]
Fixed in 2018-10-08 update

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
