### ISSUE TITLE
In-line HELM defined using ChemAxon SMILES not connected to other monomers

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#228]
If I use the following HELM strings in the HELM webeditor:

`PEPTIDE1{A.[C(=O)[C@H](C)N(*)C |$_;;;;;;;_R1;;;$]}$$$$`
`PEPTIDE1{A.[C(=O)[C@H](C)N([*])C |$_;;;;;;;_R1;;;$]}$$$$`

then it generates disconnected fragments for the structure. 

![image](https://user-images.githubusercontent.com/3986896/47101401-e0b52b00-d231-11e8-8a0b-bccd099a4a6c.png)

The webeditor should connect the monomer structures to each other.

**Comment by scilligence** [comment]
I just updated WebService to 

Monomerservice 1.1.5 https://oss.sonatype.org/content/repositories/releases/org/pistoiaalliance/helm/helm2-monomerservice/1.1.5/helm2-monomerservice-1.1.5.war
Webservice 3.0.2 https://oss.sonatype.org/content/repositories/releases/org/pistoiaalliance/helm/helm2-webservice/3.0.2/helm2-webservice-3.0.2.war

but it still cannot parse R1 correctly.  Here is ajax return value:
{"SMILES":"C(=O)[C@H](C)N([*])C |$_;;;;;;;_R1;;;$","Molfile":"|$_;;;;;;;_R1;;;$\n  CDK     11231816022D\n\n  7  6  0  0  1  0  0  0  0  0999 V2000\n    1.2990   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    2.5981   -0.0000    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0\n    2.5981    1.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8971   -0.7500    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8971   -2.2500    0.0000 *   0  0  0  0  0  0  0  0  0  0  0  0\n    5.1962   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  2  0  0  0  0 \n  1  3  1  0  0  0  0 \n  3  4  1  6  0  0  0 \n  3  5  1  0  0  0  0 \n  5  6  1  0  0  0  0 \n  5  7  1  0  0  0  0 \nM  END\n"}

**Comment by ClairePA** [comment]
Markus - could you have a look at this please? I thought CDK supported ChemAxon extended SMILES, so the R groups should be transferred?

**Comment by TianhongZhang** [comment]
The input cxsmiles is invalid. If you use the following HELM notation, it worked.

PEPTIDE1{A.[C[C@@H](C=O)N(C)[*] |$;;;;;;_R1$|]}$$$$

**Comment by ClairePA** [comment]
Ah. My bad. Close.
