### ISSUE TITLE
Webeditor needs a version number

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#235]
At present the webeditor does not have a version number within it. 

![image](https://user-images.githubusercontent.com/3986896/48349803-33d99c80-e67d-11e8-8fdc-c07f16fa281f.png)

The V2.0 relates to the HELM notation version and not the editor which is confusing. 

Please update the number, so it is the current version number.

**Comment by scilligence** [comment]
Fixed, and code checked in

**Comment by ClairePA** [comment]
Confirmed fixed.
