### ISSUE TITLE
JSON HELM is missing as an output format

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#24]
JSON HELM should be created using the toolkit web-services.

**Comment by tony-yuan** [comment]
From the HELM Editor 1.0, I cannot see this function.  Could you send me the specification of the JSON HELM format?

http://pistoiahelm.github.io/applet/HELMApplet.html

**Comment by tony-yuan** [comment]
Does JSON HELM mean the annotation section as described in the specification? 
-------------------------------------------
5.3.4	ExtendedAnnotation$
This section can be used for any additional annotation in valid JSON format.
Example: {“PEPTIDE1”:{ “ChainType”:”hc”},”PEPITDE2”:{“ChainType”:”lc”}}
5.3.4.1	Simple polymer annotations
Inline annotations of polymers are marked with quotation marks “”. They are always located after the polymer, i.e. before the separator of the next polymer.

**Comment by ClairePA** [comment]
Yes - there is a toolkit function for this, you just need to call it.

**Comment by tony-yuan** [comment]
Is there any preference on the json key for the antisense/sense field?

**Comment by TianhongZhang** [comment]
No defined rules, but how about "strandType"?

**Comment by ClairePA** [comment]
strandType is fine with me.

**Comment by scilligence** [comment]
Fixed.  Like other naming, all keys are named all lower case. e.g. 

RNA1{R(A)P.R(A)P}$$${"RNA1":{"strandtype":"ss"}}$V2.0

**Comment by ClairePA** [comment]
Looks good to me. Tianhong - can you double-check?

**Comment by ClairePA** [comment]
The antisense strand is labelled 5' at both ends. It needs to be labelled correctly.

**Comment by scilligence** [comment]
Fixed in 2017-04-29 update

**Comment by ClairePA** [comment]
Not possible to create a complementary strand, so can't check.

**Comment by scilligence** [comment]
Sorry, this was caused in my last change.  It is fixed now.

**Comment by ClairePA** [comment]
Looks OK to me - could someone check the HELM please?

**Comment by MarkusWeisser** [comment]
The naming of this issue is missleading. Conversion from HELM to JSON (http://46.101.131.62:8080/WebService/HowToUse.html#!/Conversion/createJSON ) is competely different from the JSON encoding within the HELM string itself.

**Comment by ClairePA** [comment]
The issue indeed named incorrectly, I got muddled. You also don't need a complementary strand to generate the annotation for strandtype, so it is even more wrong now. 

However, please could someone double-check that the strandtype annotation is generated correctly please? If it right then I will close this issue before it includes any more of my mistakes.

**Comment by ClairePA** [comment]
Format looks OK to me. As no one else is checking this I am going to close it.
