### ISSUE TITLE
Browser crashes and rendered sequence dissapeares

### ISSUE THREAD

**Issue by Aleksashka11** [PistoiaHELM/HELMWebEditor#242]
When I am using the code presented below, after scrolling through the web page browser crashes and rendered before sequences dissapear.
**setTimeout(function() {
      // @ts-ignore
      new JSDraw(host, { width: w, height: h, skin: "w8", viewonly: true });
    }, 200);**

**Comment by TianhongZhang** [comment]
@Aleksashka11 , how did you use the HWE? I am not sure where did that code snippet come from.

**Comment by Aleksashka11** [comment]
I'm using the provided JSDraw functionality in order to draw canvas for the stored HELM string.
Here host is a div where I actually store mentioned above HELM string as an attribute.

**Comment by Aleksashka11** [comment]
The problem is solved, it wasn't your fault.
Thank you for the attention and responses.
I am closing the issue.
