### ISSUE TITLE
Missing the ability to mark a rule as a favorite

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#25]
It should be possible to mark a rule as a favorite on a per user basis (via the browser is acceptable). Favorites should be sorted to the top of the list.

**Comment by tony-yuan** [comment]
Fixed in 2016-08-22 version

**Comment by ClairePA** [comment]
You can mark rules as favourites, but they are not sorted to the top of the list until you either leave the app and restart it.

**Comment by ClairePA** [comment]
The current approach is fine for release 1, but the update should be present in release 2. Assigned to new milestone.

**Comment by scilligence** [comment]
This is fixed.  But the change might confuse users: each time when click on it, the list reorders itself.

**Comment by ClairePA** [comment]
It may confuse users, but I prefer it, so let's leave it as it is now. 
Thanks.
