### ISSUE TITLE
helm.rule.save and helm.rule.del issues

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/HELMWebEditor#35]
When trying to save a rule, the results are URL encoded, and make the saved result unreadable. When trying to delete it, it generate a cmd helm.rule.del not supported error.

**Comment by tony-yuan** [comment]
Fixed. Two file changed:
https://github.com/tony-yuan/HELM2WebService/blob/master/src/main/java/org/helm/rest/AjaxTool.java
https://github.com/tony-yuan/HELM2WebService/blob/master/src/main/java/org/helm/rest/Database.java

**Comment by TianhongZhang** [comment]
Unable to run the service due to changes to how monomers.txt and rules.txt are handled.

**Comment by tony-yuan** [comment]
@TianhongZhang Sorry.  Your changes are recovered now.

**Comment by TianhongZhang** [comment]
I was able to save a new rule and delete an existing rule now, but the content saved is still URL encoded, which makes it hard to read and the script invalid. See rule 5 in the screenshot below. Also, I provided category in the form, but its value is not saved.

![image](https://cloud.githubusercontent.com/assets/3718858/18854961/051ea65c-841d-11e6-98d5-a95fc9c42861.png)

**Comment by tony-yuan** [comment]
Fixed.  Changes in file: https://github.com/tony-yuan/HELM2WebService/blob/master/src/main/java/org/helm/rest/AjaxTool.java

**Comment by TianhongZhang** [comment]
Category and Description are provided in the form, but not saved to the database.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-21 update

**Comment by ClairePA** [comment]
Tianhong to check.

**Comment by TianhongZhang** [comment]
confirm fixed.
