### ISSUE TITLE
Example on how to implement server side rules

### ISSUE THREAD

**Issue by scilligence** [PistoiaHELM/HELMWebEditor#36]

**Comment by tony-yuan** [comment]
Two ways to implement rules:

1. Implement server-side rules by calling web service:

            function(plugin) { 
                scil.Utils.ajax("http://SERVER/youerservice", function(ret) {
                    var new_helm = ret.new_helm;
                    plugin.setHelm(new_helm);
                });
            } 

2. Implement javascript rules using javascript APIs:

            function(plugin) {    
                var n = plugin.replaceMonomer(scil.helm.HELM.LINKER, "P", "sP");    return n > 0; 
            }

**Comment by scilligence** [comment]
The server side is re-implemented using jdbc for MySql

**Comment by ClairePA** [comment]
Now implemented in Mongodb. Close.
