### ISSUE TITLE
Monomer Editing Form issue

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/HELMWebEditor#41]
Try to open Peptide monomer 'Bal'  for editing, the form does not display R2 (should be O), and has a broken image for Element C in the toolbar.
![image](https://cloud.githubusercontent.com/assets/3718858/18896027/6a600a0e-84ec-11e6-84ad-084531d59ca7.png)

**Comment by tony-yuan** [comment]
Fixed in 2016-09-28 update

**Comment by tony-yuan** [comment]
All fixed in 2016-10-03 update

**Comment by TianhongZhang** [comment]
still only shows R1 the first time. 'Status' is not saved either.

**Comment by tony-yuan** [comment]
1. Status is removed since we don't use it.  

2. In the monomer library, the R2 and R3 are set to O, not OH.  It it why it doesn't show up.  Should O be allowed.

**Comment by TianhongZhang** [comment]
We should be consistent in the name of leaving group between Monomer Library and Monomer UI. My preference is to use OH everywhere, instead of O. If we update monomer library from O to OH, we should be all set. New monomer can only be defined using OH, not O anyway.

Related to this, the symbol/name search is not working. My search criteria returned nothing, as shown below. It should return multiple monomers.

![image](https://cloud.githubusercontent.com/assets/3718858/23146395/6609a30e-f7a4-11e6-9d14-d7c57a86827f.png)

**Comment by ClairePA** [comment]
Hi Tianhong - agree with the leaving group comment. 

Symbol/name search is working fine for me. Are you using the test version with the server side implemented? http://54.91.164.146/WebService/hwe/examples/MonomerLibApp.htm
I had to do a force refresh to get the latest version.

**Comment by ClairePA** [comment]
Hi Tianhong, 

The symbol/name search looks OK to me - could you check? It returns 'contains' for symbol and 'begins with' for name.

**Comment by ClairePA** [comment]
Leaving groups are a feature of the monomer set. Monomer set information is being handled elsewhere, so I propose closing this issue and tracking via the monomer.org activities.
