### ISSUE TITLE
New rules do not have a 'created date' 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#50]
When I create a rule manually using the ruleset manager it appears in the list without a 'created date'. this should be automatically populated.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-10 update

**Comment by ClairePA** [comment]
Confirmed fixed.

**Comment by ClairePA** [comment]
This seems to have stopped working. Created date is no longer populated.

**Comment by scilligence** [comment]
Fixed in 2017-04-29 update

New created monomers will have created date.

**Comment by ClairePA** [comment]
Confirmed fixed.
