### ISSUE TITLE
The relative sizes of structures doesn’t appear correct

### ISSUE THREAD

**Issue by scilligence** [PistoiaHELM/HELMWebEditor#52]

**Comment by tony-yuan** [comment]
I cannot reproduce this with the current monomer library.  I doubt the two structures use different bond length in Jeff's monomer library.

**Comment by ClairePA** [comment]
I can't reproduce this now either, however we still don't have the structures laid out in the way that Eric prefers. Do we have the latest version of the monomer set with the new coordinates?
If we do, please let me know and I will follow-up with Eric/Jeff.

**Comment by ClairePA** [comment]
Hi Tony, is the editor using the latest version of the monomers? the relative sizes are OK, but I don't think we are seeing the layout that Eric is after yet.

**Comment by ClairePA** [comment]
Claire to follow-up with Ionis and see if there is a new monomer library. Two issues:
- Some R groups are not detailed in the monomer definition.
- are we going to try to fix the layout for nucleotides using the monomers?

**Comment by ClairePA** [comment]
Size issue is now resolved, other monomer issues will be handled in the monomer subgroup.
