### ISSUE TITLE
Structure field in monomer page should allow more format

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#72]
When creating a new monomer, we currently can only import HELM and xHELM in the structure field. Since these are only small molecules for monomers, we should support other formats such as MOL, SMILES or even CDX just like in the current HELM editor with Marvin.

In fact, one could argue that importing HELM does not fit in the monomer structure.

**Comment by tony-yuan** [comment]
Fixed in 2016-11-02 update.  In order to do so, the server side should be able to read those file formats, and convert them into molfile.

**Comment by ypotier** [comment]
Isn't it a format that has to be supported by the chemical editor? 
Because here, we are talking about importing a chemical structure for monomers only, there is no need to have backend operation.

**Comment by tony-yuan** [comment]
1. For security reason, the browser won't let users directly open local file.  The alternative is to upload the file to the server, and the server send file contents back to the client.

2. Molfile file can be read by JSDraw.Lite.  CDX, SMILES should be converted into molfile on the server side.

**Comment by ClairePA** [comment]
I am confused - we are talking about this yes?
![image](https://cloud.githubusercontent.com/assets/3986896/19924839/9339a8f8-a0e5-11e6-81af-098c310df4d4.png)
Why can't the list of sile types include mol, SMILES etc... JS Draw on the Scilligence website covers molfile.
![image](https://cloud.githubusercontent.com/assets/3986896/19924899/c8d8e91a-a0e5-11e6-898a-ceaa4988c043.png)

**Comment by ypotier** [comment]
@ClairePA yes, this is what I am talking about. In most cases, users will import a format related to small molecules: mol, SMILES, CDXML.
The same way MarvinJS allow to open files: https://marvinjs-demo.chemaxon.com/latest/demo.html (there might be backend component here as I am not familiar with the details).

**Comment by ClairePA** [comment]
The prompt is now for small molecule formats molfile, SMILES. Close.
