### ISSUE TITLE
Start-up time is too slow with large monomer libraries 

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#75]

**Comment by ClairePA** [comment]
Need to identify the performance expectation and where the bottleneck is. How long does it take the service to produce the library? Discuss in a team meeting.

**Comment by scilligence** [comment]
There is how to initialize the App using frequently used monomer library, and delay loading all monomers:

    <div id="div1"></div>
    <script type="text/javascript">
        var app;
        // initialize the app using frequently used monomers
        scil.ready(function () {
            app = new org.helm.webeditor.App("div1", {
                monomersurl: "http://ionish.monomers.org/monomers?set=frequentlyused",
                monomersfun: readMonomer,
                mexrnapinontab: true, mexmonomerstab: false, canvastoolbar: true, mexfavoritetab: false, mexcombinedmode: true,
                mexfind: false, mexfilter: false, mexshowrnaselection: false, sequenceviewonly: false, mexrules: true, mexfavoritefirst: true, mexusecolor: true, mexuseshape: false, mexfilter: true
            });

            // then load all remained monomers from http://ionish.monomers.org/monomers?set=all
            scil.Utils.ajax("", function (ret) {
                org.helm.webeditor.Monomers.loadDB(ret, readMonomer);
            });
        });

        function readMonomer(x) {
            var m = { id: x.alternateId, n: x.name, na: x.naturalanalog, type: x.polymerType, mt: x.monomertype, m: x.molfile };

            m.at = {};
            var rs = 0;
            for (var r = 1; r <= 5; ++r) {
                if (x["R" + r]) {
                    m.at["R" + r] = x["R" + r];
                    ++rs;
                }
                else if (x["r" + r]) {
                    m.at["R" + r] = x["r" + r];
                    ++rs;
                }
            }
            m.rs = rs;
            return m;
        }
    </script>

**Comment by scilligence** [comment]
In most cases, it should fast enough to load monomers in one time.

**Comment by ClairePA** [comment]
Ionis have agreed that the start up time is fast enough for their purposes.
