### ISSUE TITLE
Chem monomer BHQ2 doesn't have R groups defined

### ISSUE THREAD

**Issue by scilligence** [PistoiaHELM/HELMWebEditor#76]
![t](https://cloud.githubusercontent.com/assets/19560173/19900680/c5670a06-a03a-11e6-849c-d76608e41776.png)

We do see two Rs in the structures, but not defined in monomer library.

This is why it complains no connecting point available when connecting it

**Comment by ClairePA** [comment]
Leave issue open, until we are confident that we have corrected all the missing R group definitions.

**Comment by ClairePA** [comment]
We are confident the monomer issues are now resolved. Close.
