### ISSUE TITLE
Dialogue boxes need to be tidier

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#81]
Could we have a general tidy up of the dialogue boxes? For example, in the load file box
![image](https://cloud.githubusercontent.com/assets/3986896/20003211/33e93f14-a27d-11e6-83b6-c4d62e451ed3.png)

the icon for the 'load file' button squashes into the icon making it look untidy. 
The height of the Browse button is less than the load file button and looks squashed. 

Examples of layouts where there is consistency given below:
![image](https://cloud.githubusercontent.com/assets/3986896/20003528/d60526f4-a27e-11e6-9b26-1ba078811457.png)

![image](https://cloud.githubusercontent.com/assets/3986896/20003676/bd6fc774-a27f-11e6-8702-8a93057af9d6.png)

Save and load dialogue boxes should have an explicit cancel button.
![image](https://cloud.githubusercontent.com/assets/3986896/20003727/f0abfe0a-a27f-11e6-8da5-2a5c77ce5caa.png)
I would prefer just the work 'save' rather than 'save file' and the tick is not really adding a lot.

**Comment by scilligence** [comment]
1. The Browse... button is part of the file selecting control, which is a part of the browser internal design.  We cannot change it.

2. Cancel button is added.  By the way, the dialog X button, and keyboard ESC key can be used to close the dialog as well.

**Comment by scilligence** [comment]
Fixed in 2016-12-15 update

**Comment by ClairePA** [comment]
Import and export now gives me a space to copy/paste into. This is probably fine for a HELM string, but becomes cumbersome for xHELM. why did it change?

**Comment by scilligence** [comment]
The web service is not configured on site http://54.91.164.146/WebService/HWE.html, so import/export won't be able to to read/write files.

The demo site http://elncloud.com/helm/helm/App.htm does have web service configured, so it will popup file dialog to read/write files.

**Comment by ClairePA** [comment]
I thought http://54.91.164.146/WebService/HWE.html , was fully configured? How do we get this to a point where it can be tested?

**Comment by ClairePA** [comment]
Services are now configured and test and demo sites set up.
