### ISSUE TITLE
Highlighted monomers are not displayed

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#90]
When I click (or double-click) on a monomer the information about that monomer is rarely displayed in the boxes underneath. 

![image](https://cloud.githubusercontent.com/assets/3986896/22418519/468319fe-e6d1-11e6-8c49-027748f3cf56.png)

Occasionally monomer information is displayed, but this is inconsistent and rare.

**Comment by ypotier** [comment]
Hi Claire, I did not see the problem on Chrome. What browser are you using?

**Comment by ClairePA** [comment]
Edge – interesting that you don’t see it. I will update the issue with the fact that you are OK using Chrome. 

 

Thanks Yohann, 

 

Claire

**Comment by scilligence** [comment]
I tested it with my Edge, and cannot reproduce it.

**Comment by scilligence** [comment]
Could you try it again, since it is updated?

**Comment by ClairePA** [comment]
This works fine now - thanks.
