### ISSUE TITLE
Monomers are not ordered by name or symbol

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#91]
If I page through the monomer list it looks like it is in alphabetical order by symbol, however this is deceptive. If I continue to scroll through the order is not consistent. 

Please allow the user to order the lists by symbol or name.

**Comment by scilligence** [comment]
It is ordered by symbol

**Comment by ClairePA** [comment]
No it isn't, Earlier pages appear to be, but later ones show that the ordering is not consistent. 
![image](https://cloud.githubusercontent.com/assets/3986896/23025372/a7e230a4-f455-11e6-9613-4cea72947f95.png)

**Comment by scilligence** [comment]
This is server side code.  Since we are revamping it to connect to real database, we leave it for now.

**Comment by scilligence** [comment]
Fixed on test site

**Comment by ClairePA** [comment]
Confirmed fixed. Thanks.
