### ISSUE TITLE
The monomer manager does not include SMILES

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#93]
The chemical structure is displayed, however the SMILES string is not shown. The user may want to copy/paste the SMILES so it should be shown. It would also allow the user to check that the SMILES and molfile show the same information.

**Comment by scilligence** [comment]
SMILES and molfile are redundant.   I would suggest to dynamical generate SMILES from molfile if needed.   If we have two fields to SMILES molfile, we need handle the case when SMILES has a different structure from Molfile.

**Comment by ClairePA** [comment]
Discussion with the team indicates that SMILES are not redundant and there are other functions within the toolkit which require SMILES and keep the molfile and SMILES in sync, so there should not be a problem of different structures if the toolkit is used.

**Comment by scilligence** [comment]
SMILES is added

**Comment by ClairePA** [comment]
Thanks - the box looks a bit big for a SMILES string. Could you make it smaller please? 

![image](https://cloud.githubusercontent.com/assets/3986896/23300076/e86f66c4-fa7b-11e6-9ab7-158fcf7039f4.png)

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
Perfect - thanks.
