### ISSUE TITLE
Can't export monomers

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#94]
It should be possible to export all monomer or the current monomer highlighted.

**Comment by scilligence** [comment]
Could you specify detailed requirements on this?

- What format it should be?
- What is the user case?

**Comment by ClairePA** [comment]
The export should contain all the monomer information in the agreed format as defined in  http://www.scilligence.com/sdk/helm/logical/org/helm/webeditor/MonomerLibApp.html
The export should be available as:
- JSON
- SDF

**Comment by scilligence** [comment]
JSON is done

**Comment by ClairePA** [comment]
Thanks for the single monomer JSON.

**Comment by scilligence** [comment]
SDF is ready now

**Comment by ClairePA** [comment]
sdf format incorrect. You have added $$$$ after the molfile, so the data is separated from the structure and throws an error. 

![image](https://cloud.githubusercontent.com/assets/3986896/23701406/84c16eb6-03ee-11e7-822c-263611a08f12.png)


Nice to have suggestion - could the export include the monomers in the current search list rather than all monomers?

**Comment by scilligence** [comment]
Fixed.  This is a toolkit bug

**Comment by ClairePA** [comment]
The extra $$$$ is now fixed, but the tool I am using to check does not like the absence of a carriage return after the $$$$ when where is a 'no structure' molecule - see Alexa. 

Quick question - is the fix added to the toolkit or worked around in the editor?

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
Confirmed fixed.
