### ISSUE TITLE
monomers are not scaled to the correct size if they are entered differently

### ISSUE THREAD

**Issue by gwas** [PistoiaHELM/HELMWebEditor#97]
If users enter a heterocycle with different sizes the viewer doesn't correct this to a standard size.  For example.  ACTG the bases might be entered with different C-C bond lengths this is not corrected to the same "relative" size so we end up with large "C"'s and small T's etc.

**Comment by ClairePA** [comment]
See below for an example of the issue. As agreed in the team meeting, monomers should be scaled to a common bond length at the point that they are displayed in the structure view. 

![image](https://cloud.githubusercontent.com/assets/3986896/26363010/a2c2ea8c-3fd7-11e7-8e51-9f9d56b8f933.png)

**Comment by scilligence** [comment]
fixed in 2017-06-08 update

**Comment by ClairePA** [comment]
Confirmed fixed - thanks!
