### ISSUE TITLE
Alphabetical ordering of monomers is not working

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#98]
The previous version of the monomer manager ordered the monomers by Symbol. The latest update seems to have lost this. 

![image](https://cloud.githubusercontent.com/assets/3986896/24698199/acf7c5c4-19e7-11e7-8b6d-e97acb927a6e.png)

Filtering by symbol or name is not working either.

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
Ordering is fixed, but the filtering by symbol/name is not fixed.

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
The filtering is now an exact match, whereas I believe we asked for 'starts with'.

**Comment by ClairePA** [comment]
Contains means that you get a very wide number of results when looking for a simple monomer. For example searching for R gives Serine as a result which is not intuitive. I would prefer the symbol and name search to be separated, if this is not possible then the search must be a 'starts with' However combining name and symbol searches will always be confusing.

**Comment by scilligence** [comment]
It uses *contains* for Symbol, and *starts with* for Name.  For example, when user types A, it can match mA

**Comment by ClairePA** [comment]
OK, that seems reasonable. I still think it would be better to separate the symbol and name searching to make it clearer, but we will wait and see if anyone requests this before actually doing anything.
