### ISSUE TITLE
There is no validation on new monomers

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#99]
It is possible to add a monomer with incorrect information. The following should be checked before the monomer is saved. 

- R groups in the sketch and the capping groups match. (I  defined a chemical sketch containing 3 R groups, but only one capping group was added and it was possible to save it.)

- SMILES should be generated to ensure that the SMILES matches the mofile, currently it is not generated at all.

**Comment by scilligence** [comment]
Fixed

**Comment by ClairePA** [comment]
The check looks for missing R groups, but should also check if too many R groups have capping groups defined. 

The SMILES is not yet generated.

**Comment by scilligence** [comment]
fixed

**Comment by ClairePA** [comment]
The check for missing R groups is now correct. However, when I try to save the following monomer:

![image](https://cloud.githubusercontent.com/assets/3986896/25240354/7c997ec2-25ea-11e7-9263-ff668dc133b7.png)

I get this error. 

![image](https://cloud.githubusercontent.com/assets/3986896/25240285/55557154-25ea-11e7-8ea6-955c4a0b10c6.png)

**Comment by scilligence** [comment]
Sorry. Fixed now

**Comment by ClairePA** [comment]
Thanks, the R group tests now work, but the SMILES is not generated.

**Comment by scilligence** [comment]
Fixed in 2017-05-05 update

**Comment by ClairePA** [comment]
Confirmed fixed.
